import { buildSchedule } from "@/lib/scheduler";
import type { Family, NightSettings, Teacher } from "@/lib/types";

export const seedSettings: NightSettings = {
  schoolName: "Maplewood Elementary",
  title: "Fall Conferences",
  date: "2026-10-22",
  startTime: "16:00",
  endTime: "19:00",
  slotMinutes: 15,
  maxGapMinutes: 30,
};

export const seedTeachers: Teacher[] = [
  { id: "t-chen", name: "Avery Chen", role: "Grade 2 Homeroom", room: "Room 12" },
  { id: "t-alvarez", name: "Mateo Alvarez", role: "Grade 2 Homeroom", room: "Room 14" },
  { id: "t-patel", name: "Priya Patel", role: "Grade 3 Homeroom", room: "Room 18" },
  { id: "t-brooks", name: "Jordan Brooks", role: "Grade 4 Homeroom", room: "Room 22" },
  { id: "t-okonkwo", name: "Nia Okonkwo", role: "Reading Specialist", room: "Room 8" },
  { id: "t-singh", name: "Raj Singh", role: "Math Support", room: "Room 9" },
  { id: "t-rivera", name: "Camila Rivera", role: "Visual Art", room: "Studio A" },
  { id: "t-hale", name: "Owen Hale", role: "Music", room: "Music Room" },
  { id: "t-diaz", name: "Lena Diaz", role: "Physical Education", room: "Gym" },
  { id: "t-walsh", name: "Helen Walsh", role: "Learning Support", room: "Room 6" },
  { id: "t-ito", name: "Yuki Ito", role: "Language Support", room: "Room 4" },
  { id: "t-berg", name: "Dana Berg", role: "School Counselor", room: "Office" },
];

export const seedFamilies: Family[] = [
  {
    id: "f-ruiz",
    familyName: "Ruiz",
    guardian: "Alex Ruiz",
    student: "Elena",
    grade: "2",
    teacherIds: ["t-chen", "t-okonkwo", "t-rivera"],
  },
  {
    id: "f-park",
    familyName: "Park",
    guardian: "Grace Park",
    student: "Noah",
    grade: "2",
    teacherIds: ["t-chen", "t-singh", "t-hale"],
  },
  {
    id: "f-mensah",
    familyName: "Mensah",
    guardian: "Kwame Mensah",
    student: "Ama",
    grade: "2",
    teacherIds: ["t-chen", "t-okonkwo"],
  },
  {
    id: "f-gallagher",
    familyName: "Gallagher",
    guardian: "Casey Gallagher",
    student: "Finn",
    grade: "2",
    teacherIds: ["t-chen", "t-diaz", "t-rivera"],
  },
  {
    id: "f-cho",
    familyName: "Cho",
    guardian: "Min Cho",
    student: "Mina",
    grade: "2",
    teacherIds: ["t-chen", "t-ito", "t-berg"],
  },
  {
    id: "f-haddad",
    familyName: "Haddad",
    guardian: "Lina Haddad",
    student: "Lila",
    grade: "2",
    teacherIds: ["t-alvarez", "t-okonkwo", "t-hale"],
  },
  {
    id: "f-okafor",
    familyName: "Okafor",
    guardian: "Chidi Okafor",
    student: "Tunde",
    grade: "2",
    teacherIds: ["t-alvarez", "t-singh"],
  },
  {
    id: "f-bennett",
    familyName: "Bennett",
    guardian: "Sam Bennett",
    student: "Willa",
    grade: "2",
    teacherIds: ["t-alvarez", "t-rivera", "t-diaz"],
  },
  {
    id: "f-nguyen",
    familyName: "Nguyen",
    guardian: "Hannah Nguyen",
    student: "Kai",
    grade: "2",
    teacherIds: ["t-alvarez", "t-okonkwo", "t-walsh"],
  },
  {
    id: "f-rossi",
    familyName: "Rossi",
    guardian: "Elena Rossi",
    student: "Nico",
    grade: "2",
    teacherIds: ["t-alvarez", "t-hale", "t-berg"],
  },
  {
    id: "f-bergstrom",
    familyName: "Bergstrom",
    guardian: "Astrid Bergstrom",
    student: "Freya",
    grade: "3",
    teacherIds: ["t-patel", "t-singh", "t-okonkwo"],
  },
  {
    id: "f-ali",
    familyName: "Ali",
    guardian: "Noor Ali",
    student: "Yasmin",
    grade: "3",
    teacherIds: ["t-patel", "t-rivera", "t-ito"],
  },
  {
    id: "f-kowalski",
    familyName: "Kowalski",
    guardian: "Piotr Kowalski",
    student: "Marek",
    grade: "3",
    teacherIds: ["t-patel", "t-hale", "t-diaz"],
  },
  {
    id: "f-washington",
    familyName: "Washington",
    guardian: "Jordan Washington",
    student: "June",
    grade: "3",
    teacherIds: ["t-patel", "t-walsh", "t-okonkwo"],
  },
  {
    id: "f-sharma",
    familyName: "Sharma",
    guardian: "Anika Sharma",
    student: "Arjun",
    grade: "3",
    teacherIds: ["t-patel", "t-singh", "t-berg"],
  },
  {
    id: "f-deluca",
    familyName: "DeLuca",
    guardian: "Marco DeLuca",
    student: "Sofia",
    grade: "4",
    teacherIds: ["t-brooks", "t-singh", "t-rivera"],
  },
  {
    id: "f-thompson",
    familyName: "Thompson",
    guardian: "Riley Thompson",
    student: "Ellis",
    grade: "4",
    teacherIds: ["t-brooks", "t-okonkwo", "t-diaz"],
  },
  {
    id: "f-ibrahim",
    familyName: "Ibrahim",
    guardian: "Fatima Ibrahim",
    student: "Hana",
    grade: "4",
    teacherIds: ["t-brooks", "t-hale", "t-walsh"],
  },
  {
    id: "f-mcrae",
    familyName: "McRae",
    guardian: "Owen McRae",
    student: "Callum",
    grade: "4",
    teacherIds: ["t-brooks", "t-singh", "t-berg"],
  },
  {
    id: "f-flores",
    familyName: "Flores",
    guardian: "Camila Flores",
    student: "Mateo",
    grade: "4",
    teacherIds: ["t-brooks", "t-rivera", "t-ito", "t-okonkwo", "t-singh"],
  },
];

export function makeSeedSchedule() {
  return buildSchedule(seedTeachers, seedFamilies, seedSettings);
}
