/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliesRouteImport } from './routes/families'
import { Route as PrintRouteImport } from './routes/print'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TeachersRouteImport } from './routes/teachers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesRoute = FamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/families': typeof FamiliesRoute
  '/print': typeof PrintRoute
  '/schedule': typeof ScheduleRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/families': typeof FamiliesRoute
  '/print': typeof PrintRoute
  '/schedule': typeof ScheduleRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/families': typeof FamiliesRoute
  '/print': typeof PrintRoute
  '/schedule': typeof ScheduleRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/families' | '/print' | '/schedule' | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/families' | '/print' | '/schedule' | '/teachers'
  id: '__root__' | '/' | '/families' | '/print' | '/schedule' | '/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamiliesRoute: typeof FamiliesRoute
  PrintRoute: typeof PrintRoute
  ScheduleRoute: typeof ScheduleRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families': {
      id: '/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamiliesRoute: FamiliesRoute,
  PrintRoute: PrintRoute,
  ScheduleRoute: ScheduleRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
